version: '3'

services:
  ignite-api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 50432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=nodejs-solid